version: "{build}"
clone_folder: c:\gopath\src\github.com\askovpen\goated
clone_depth: 1

branches:
  only:
    - master
    - /^goated-.*/

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.10

before_build:
  - go get github.com/jroimartin/gocui
  - go get golang.org/x/text/transform
  - go get gopkg.in/yaml.v2
  - go get github.com/smartystreets/goconvey/convey

build_script:
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOOS=linux)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-lnx64.zip goated config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOARCH=386)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-lnx32.zip goated config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOOS=darwin)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-osx32.zip goated config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOARCH=amd64)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-osx64.zip goated config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOOS=freebsd)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-fbsd64.zip goated config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOARCH=386)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-fbsd32.zip goated config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOOS=windows)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (go build -v -ldflags "-w -s")
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-win32.zip goated.exe config.example.yml)
  - IF "%APPVEYOR_REPO_TAG%" == "true" (set GOARCH=amd64)
  - go build -v -ldflags "-w -s"
  - IF "%APPVEYOR_REPO_TAG%" == "true" (7z a %APPVEYOR_REPO_TAG_NAME%-win64.zip goated.exe config.example.yml)

test_script:
  - go test ./... -v -cover -race

artifacts:
  - path: "*.zip"
    name: dist

deploy:
  provider: GitHub
  artifact: dist
  auth_token: $(GITHUB_OAUTH_TOKEN)
  on:
    appveyor_repo_tag: true
